version: '3'

services:
  petriuk-h2db:
    image: oscarfonts/h2:alpine
    volumes:
      - "./db:/opt/h2-data"

  petriuk-keycloak:
    image: quay.io/keycloak/keycloak:12.0.3
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    command: 
      -Djboss.socket.binding.port-offset=10 -Dkeycloak.forceBackendUrlToFrontendUrl=true
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090/auth
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/usersapp-realm.json
      - CLIENT_URL=http://localhost:4200
    ports:
      - 8090:8090

  petriuk-roles-api:
    build: ./roles-api
    ports:
      - "8070:8080"
    depends_on:
      - petriuk-h2db
      - petriuk-keycloak

  petriuk-users-api:
    build: ./users-api
    ports:
      - "8080:8080"
    depends_on:
      - petriuk-h2db
      - petriuk-roles-api
      - petriuk-keycloak

  petriuk-angular-app:
    build: ./angular-app
    depends_on:
      - petriuk-users-api
      - petriuk-roles-api
      - petriuk-keycloak
    ports:
      - "4200:4200"
