INSERT INTO USER_ROLES ( NAME ) VALUES ('user');
INSERT INTO USER_ROLES ( NAME ) VALUES ('admin');

INSERT INTO USER_ACCOUNTS ( LOGIN , PASSWORD , EMAIL , FIRST_NAME , LAST_NAME , BIRTHDAY , ROLE_ID )
VALUES ( 'user', '$2a$10$XvMg6VqTOoAw0IAvjUwZJeos481LGhCiIqoyFNjt6HeuyOcUW3ogW', 'u@ser.net', 'John', 'Smith', '1980-01-01', '1');
INSERT INTO USER_ACCOUNTS ( LOGIN , PASSWORD , EMAIL , FIRST_NAME , LAST_NAME , BIRTHDAY , ROLE_ID ) 
VALUES ( 'admin', '$2a$10$zoeDoGTVFfRL8p9AnK6foeBis9jHhGReUA989NuqIFASyPvzVSora', 'a@dmin.net', 'Sarah', 'Connor', '1970-02-08', '2');
